### ISSUE TITLE
Bolt doesn't respond in Revolt

### ISSUE THREAD

**Issue by RainbowTH1** [williamhorning/bolt#26]
~~why am I doing this~~

For some reason, the bot goes offline for a brief period after I try `!bolt help`, almost as if it's crashing.
I do not know what is causing this issue, but I haven't been able to get another bot to work either.

**Comment by williamhorning** [comment]
It's probably crashing due to issues that can't really be fixed in the current codebase. bolt 0.5 should fix these sorts of issues though
