### ISSUE TITLE
telegram bridge

### ISSUE THREAD

**Issue by aicynide** [williamhorning/bolt#39]

**Comment by williamhorning** [comment]
after taking a look at other bots that handle telegram bridging, there'll be a fair bit of work required for this:

- markdown <=> html parsing (multiple node packages can do this, haven't looked too far into deno options)
- finding a telegram api package that's actively maintained
- actually finding the best way to bridge messages and rich-content associated with them
- implementing commands in a sane, user-friendly way

if you have any advice for any of these points, please let me know!

**Comment by williamhorning** [comment]
hey there! i just added telegram support into the codebase for 0.7.1, but the actual hosted bot will take a bit to get telegram support as i have to test everything before making the actual release
