### ISSUE TITLE
Bolt becomes one-way in channels it can't see

### ISSUE THREAD

**Issue by SpectrumUK703** [williamhorning/bolt#4]
Messages sent in Discord channels bolt can't see don't get sent to Guilded

**Comment by williamhorning** [comment]
This is a permission error, no doubt about it. I could probably improve the docs to point out that Bolt needs to see channels to bridge right, but the UX for this kinda sucks and could be improved with ADBs

**Comment by Magesw** [comment]
> Messages sent in Discord channels bolt can't see don't get sent to Guilded

This is how it should be, if the bot can't see the channel how is it supposed to know what to transfer over?

**Comment by williamhorning** [comment]
closing because i cant fix this, tbh
