### ISSUE TITLE
Discord and Guilded invitations in docs are invalid or expired

### ISSUE THREAD

**Issue by halian** [williamhorning/bolt#42]
Per topic.

**Comment by williamhorning** [comment]
Oh whoops, I forgot that this was an issue. I'll update the docs to use new links sometime this weekend

**Comment by williamhorning** [comment]
fixed in f886129d71d41734bd45f52bae675c79cc4caaf7 and 3136d561d5efe80d88072f3a0bc8a2ab6deb6ee9 with https://github.com/williamhorning/williamhorning/commit/27f2d51a522cb17f87354b1322a5131c06206331 starting the site rebuild
