### ISSUE TITLE
Replies on Guilded to messages from Discord don't get sent to Discord

### ISSUE THREAD

**Issue by SpectrumUK703** [williamhorning/bolt#6]

**Comment by williamhorning** [comment]
Can't repro, can you send me the channel IDs and message IDs that're affected?

**Comment by Magesw** [comment]
Tested this myself and it doesn't work.
Discord channel ID:  161683252405338113
Guilded channel ID: dc10ad2d-5fb8-4abc-b2a7-07472d30fbf9

![image](https://user-images.githubusercontent.com/13952888/191863996-cd821f14-4f01-482a-a795-a2c1f884c08c.png)
![image](https://user-images.githubusercontent.com/13952888/191864025-363138d7-9e47-4380-9c1d-cdea4afe5a17.png)

**Comment by williamhorning** [comment]
Oh wait, this affects webhook bridges since Guilded doesn't give in-message author data for webhooks, and we can't get webhook author info

**Comment by chalkycroissant** [comment]
Is this still the way guilded's webhooks function? just wondering :)

**Comment by williamhorning** [comment]
@chalkycroissant yep, it's still a Guilded issue. Literally no other platform that bolt supports right now has this issue

**Comment by williamhorning** [comment]
solved in #8

**Comment by williamhorning** [comment]
no wait, not solved
wrong issue

**Comment by williamhorning** [comment]
currently working on a temporary fix for this where it will try other things like the author's id or display name before erroring out
