### ISSUE TITLE
Bolt wont mirror photos or gifs from discord into guilded 

### ISSUE THREAD

**Issue by chalkycroissant** [williamhorning/bolt#7]
The opposite (guilded into discord) does work though.

**Comment by williamhorning** [comment]
The images issue will be partially fixed in the near(ish) future for regular images, though the way that Discord does gifs is a bit weird, so I don't see a sane way of handling that

**Comment by williamhorning** [comment]
7de1cf2bcc2c495cbd8c53545d689b6a0dcb3126 fixes the images issue in a kinda meh way, sadly that branch needs a lot more work before I can merge it into main
